version: '3'

networks:
    nginx-php8-mysql8-node-redis:

services:

    # nginx
    service-nginx:
        image: nginx:stable-alpine
        ports:
            - "8080:80"
        volumes:
            - ./app/backend/:/var/www/app
            - ./docker/volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - service-php81
            - service-mysql8
            - service-node
        networks:
            - nginx-php8-mysql8-node-redis

    # php
    service-php81:
        build:
            context: .
            dockerfile: docker/Dockerfile-Php
        volumes:
            - ./app/backend:/var/www/app
            - ./docker/volumes/php/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        networks:
            - nginx-php8-mysql8-node-redis

    # mysql
    service-mysql8:
        image: mysql:8
        ports:
            - "4306:3306"
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always 
        environment:
            MYSQL_ROOT_PASSWORD: XXXX-MYSQL-DUMMY-PASSWORD-XXXX
            MYSQL_PASSWORD: XXXX-MYSQL-DUMMY-PASSWORD-XXXX
        networks:
            - nginx-php8-mysql8-node-redis

    # node
    service-node:
        image: node:19-alpine
        volumes:
            - ./app/frontend:/app
        # sh -c "sleep infinity"
        command: sh -c "cd /app && npm install --silent && npm start"
        restart: always
        ports:
            - '8081:8081'
        networks:
            - nginx-php8-mysql8-node-redis

    # redis
    service-redis:
        image: redis:6.2-alpine
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass XXXX-REDIS-DUMMY-PASSWORD-XXXX
        volumes: 
            - cache:/data
        networks:
            - nginx-php8-mysql8-node-redis

volumes:
    cache:
        driver: local # @see: https://docs.docker.com/storage/volumes/#use-a-volume-driver
