version: '3'

networks:
    nginx-php8-mysql8-node-redis:

services:

    # nginx
    service-nginx:
        image: nginx:stable-alpine
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/app
            - ./env/volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - service-php81
            - service-mysql8
        networks:
            - nginx-php8-mysql8-node-redis

    # php
    service-php81:
        build:
            context: .
            dockerfile: ./env/php/Dockerfile
        container_name: php81-container-2
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/app
        networks:
            - nginx-php8-mysql8-node-redis

    # mysql
    service-mysql8:
        image: mysql:8
        ports:
            - "4306:3306"
        volumes:
            - ./env/volumes/mysql/var/lib/mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always 
        environment:
            MYSQL_ROOT_PASSWORD: XXXX-MYSQL-DUMMY-PASSWORD-XXXX
            MYSQL_PASSWORD: XXXX-MYSQL-DUMMY-PASSWORD-XXXX
        networks:
            - nginx-php8-mysql8-node-redis

    # node
    service-node:
        image: node:latest
        volumes:
            - ./app:/var/www/app
        working_dir: /var/www/app
        networks:
            - nginx-php8-mysql8-node-redis

    # redis
    service-redis:
        image: redis:6.2-alpine
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass XXXX-REDIS-DUMMY-PASSWORD-XXXX
        volumes: 
            - cache:/data
        networks:
            - nginx-php8-mysql8-node-redis

volumes:
    cache:
        driver: local # @see: https://docs.docker.com/storage/volumes/#use-a-volume-driver
